//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamLineDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileInformation
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public int UserId { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string Gender { get; set; }
        public string AboutMe { get; set; }
        public string Password { get; set; }
        public string TwitterConnect { get; set; }
        public string InstagramConnect { get; set; }
    }
}
